name: ticket_stopper
description: Ticket Stopper App

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.11+11

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  dotted_border: ^1.0.7
  image_picker: ^0.7.3
  vibration: ^1.7.3
  dio: ^4.0.0-prev3
  fluttertoast: ^8.0.3
  device_info: ^2.0.0
  flutter_facebook_auth: ^3.2.0
  shared_preferences: ^2.0.5
  intl: ^0.17.0
  google_sign_in: ^5.0.1
  firebase_auth: ^1.0.1
  firebase_core: ^1.0.2
  cached_network_image: ^3.0.0
  modal_progress_hud: ^0.1.3
  sign_in_with_apple: ^3.0.0
  http: ^0.13.3
  flutter_inapp_purchase: ^4.0.0
  connectivity: ^3.0.6
  url_launcher: ^6.0.7
  mailto: ^2.0.0
  in_app_purchase: ^1.0.6


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true


  assets:
     - assets/icons/

  fonts:
   - family: Poppins
     fonts:
       - asset: assets/fonts/Poppins-Regular.ttf
   - family: Acaslon
     fonts:
       - asset: assets/fonts/ACaslonPro-Regular.otf

